version: "3"

services:

  serv:
    build: "./serv"
    hostname: "serv"
    ports:
      - 80:80
      - 443:443
    depends_on:
      - db
      - php

  db:
    build: ./db
    hostname: "db"
    environment:
       - "MYSQL_DATABASE=armbook"
       - "MYSQL_ALLOW_EMPTY_PASSWORD=yes"

  php:
    build: ./php
    hostname: "php"
