version: '3'

services:
    cache:
        build: './cache-server'
        ports:
            - '80:8080'
        depends_on:
            - web-server
    web-server:
        build: './web-server'
        volumes:
            - './web-server/src/:/usr/share/nginx/html'
