 # Run NGINX on port 80 with index.html and anything else in src.
 # Used for both web servers
 FROM nginx:latest
 #COPY src/ /usr/share/nginx/html
 COPY nginx.conf /etc/nginx/conf.d/default.conf
 EXPOSE 80